# Generated by Django 5.2.5 on 2026-01-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accontspayableledgerdata',
            name='user_name',
            field=models.CharField(blank=True, help_text='Username captured from the Trade Finance UI', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accontspayableledgerdata',
            name='abn',
            field=models.CharField(blank=True, help_text='Australian Business Number (ABN)', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='accontspayableledgerdata',
            name='amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount due', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='accontspayableledgerdata',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Invoice number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accontspayableledgerdata',
            name='repayment_date',
            field=models.DateField(blank=True, help_text='Expected repayment date', null=True),
        ),
        migrations.AlterField(
            model_name='accontspayableledgerdata',
            name='supplier',
            field=models.CharField(blank=True, help_text='Creditor / supplier name', max_length=255, null=True),
        ),
    ]
