# Generated by Django 5.2.5 on 2025-10-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrawdownData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('drawdown_time', models.DateTimeField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('abn', models.CharField(blank=True, max_length=20, null=True)),
                ('acn', models.CharField(blank=True, max_length=20, null=True)),
                ('bankstatements_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('bureau_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('accounting_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('ppsr_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('originator', models.CharField(blank=True, max_length=2000, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('product', models.CharField(blank=True, max_length=2000, null=True)),
                ('insurance_premiums', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'efs_drawdowns_drawdowndata',
            },
        ),
        migrations.CreateModel(
            name='IPF_DrawdownData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('drawdown_time', models.DateTimeField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('abn', models.CharField(blank=True, max_length=20, null=True)),
                ('acn', models.CharField(blank=True, max_length=20, null=True)),
                ('bankstatements_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('bureau_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('accounting_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('ppsr_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('originator', models.CharField(blank=True, max_length=2000, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('product', models.CharField(blank=True, max_length=2000, null=True)),
                ('insurance_premiums', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'efs_drawdowns_ipf_drawdowndata',
            },
        ),
        migrations.CreateModel(
            name='scf_DrawdownData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('drawdown_time', models.DateTimeField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('abn', models.CharField(blank=True, max_length=20, null=True)),
                ('acn', models.CharField(blank=True, max_length=20, null=True)),
                ('bankstatements_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('bureau_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('accounting_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('ppsr_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('originator', models.CharField(blank=True, max_length=2000, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('product', models.CharField(blank=True, max_length=2000, null=True)),
                ('insurance_premiums', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'efs_drawdowns_scf_drawdowndata',
            },
        ),
        migrations.CreateModel(
            name='tf_DrawdownData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('drawdown_time', models.DateTimeField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('abn', models.CharField(blank=True, max_length=20, null=True)),
                ('acn', models.CharField(blank=True, max_length=20, null=True)),
                ('bankstatements_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('bureau_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('accounting_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('ppsr_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('originator', models.CharField(blank=True, max_length=2000, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('product', models.CharField(blank=True, max_length=2000, null=True)),
                ('insurance_premiums', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'efs_drawdowns_tf_drawdowndata',
            },
        ),
    ]
