# Generated by Django 5.2.5 on 2025-10-21 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrawdownData',
            new_name='if_DrawdownData',
        ),
    ]
