# Generated by Django 5.2.5 on 2025-10-21 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_drawdowndata_if_drawdowndata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='if_drawdowndata',
            table='efs_drawdowns_if_drawdowndata',
        ),
    ]
