# Generated by Django 5.2.5 on 2025-08-21 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invoicedata',
            table='efs_financial_invoicedata',
        ),
        migrations.AlterModelTable(
            name='ledgerdata',
            table='efs_financial_ledgerdata',
        ),
        migrations.AlterModelTable(
            name='scf_invoicedata',
            table='efs_financial_scf_invoicedata',
        ),
        migrations.AlterModelTable(
            name='tf_invoicedata',
            table='efs_financial_tf_invoicedata',
        ),
    ]
