# Generated by Django 5.2.5 on 2025-08-18 03:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPF_ApplicationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('application_time', models.DateTimeField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('abn', models.CharField(blank=True, max_length=20, null=True)),
                ('acn', models.CharField(blank=True, max_length=20, null=True)),
                ('bankstatements_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('bureau_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('accounting_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('ppsr_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('originator', models.CharField(blank=True, max_length=2000, null=True)),
                ('amount_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('product', models.CharField(blank=True, max_length=2000, null=True)),
                ('insurance_premiums', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
