# Generated by Django 5.2.5 on 2025-10-03 02:17

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chunking', '0003_element_document_extractionrun_document_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vector', pgvector.django.vector.VectorField(dimensions=768)),
                ('model_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='chunking.element')),
            ],
            options={
                'indexes': [models.Index(fields=['model_name'], name='embeddings__model_n_129096_idx')],
            },
        ),
    ]
