# Generated by Django 5.2.5 on 2025-10-02 08:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunking', '0002_element_extractionrun_and_more'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('ticker_symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('fiscal_year', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('upload', 'upload'), ('web', 'web'), ('api', 'api')], default='upload', max_length=50)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('byte_size', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('sheet_names', models.JSONField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AnnualReport',
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company_name', 'fiscal_year'], name='ingestion_d_company_a44ad5_idx'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ingestion.document'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='documentfile',
            index=models.Index(fields=['sha256'], name='ingestion_d_sha256_a01ee7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentfile',
            unique_together={('document', 'version')},
        ),
    ]
