# Generated by Django 5.2.5 on 2026-02-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawdown',
            name='originator',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='invoicerepayments',
            name='originator',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='transactiondetails',
            name='originator',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='transactionledger',
            name='originator',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
