# Generated by Django 5.2.5 on 2026-02-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_drawdown_originator_invoicerepayments_originator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetails',
            name='acn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transactionledger',
            name='acn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
