# Generated by Django 5.2.5 on 2026-02-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transactiondetails_acn_transactionledger_acn'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawdown',
            name='acn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoicerepayments',
            name='acn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
