# Generated by Django 5.2.5 on 2025-10-15 23:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productsglobalsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ABN', models.CharField(blank=True, max_length=100, null=True)),
                ('transactionID', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('Insolvencies', models.BooleanField(blank=True, default=False, null=True)),
                ('Insolvencies_state', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=100, null=True)),
                ('Payment_Defaults', models.BooleanField(blank=True, default=False, null=True)),
                ('Payment_Defaults_state', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=100, null=True)),
                ('Mercantile_Enquiries', models.BooleanField(blank=True, default=False, null=True)),
                ('Mercantile_Enquiries_state', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=100, null=True)),
                ('Court_Judgements', models.BooleanField(blank=True, default=False, null=True)),
                ('Court_Judgements_state', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=100, null=True)),
                ('ATO_Tax_Default', models.BooleanField(blank=True, default=False, null=True)),
                ('ATO_Tax_Default_state', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=100, null=True)),
                ('Loans', models.BooleanField(blank=True, default=False, null=True)),
                ('Loans_state', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=100, null=True)),
                ('ANZSIC', models.BooleanField(blank=True, default=False, null=True)),
                ('ANZSIC_state', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=100, null=True)),
                ('Credit_score_threshold', models.CharField(blank=True, max_length=100, null=True)),
                ('Credit_score_threshold_state', models.CharField(blank=True, choices=[('below', 'Below Threshold'), ('above', 'Above Threshold')], default='above', max_length=100, null=True)),
                ('Sales_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
