# Generated by Django 5.2.5 on 2025-08-21 03:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('application_time', models.DateTimeField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('abn', models.CharField(blank=True, max_length=20, null=True)),
                ('acn', models.CharField(blank=True, max_length=20, null=True)),
                ('bankstatements_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('bureau_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('accounting_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('ppsr_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('originator', models.CharField(blank=True, max_length=2000, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('product', models.CharField(blank=True, max_length=2000, null=True)),
                ('insurance_premiums', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'efs_sales_applicationdata',
            },
        ),
        migrations.CreateModel(
            name='IPF_ApplicationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('application_time', models.DateTimeField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('abn', models.CharField(blank=True, max_length=20, null=True)),
                ('acn', models.CharField(blank=True, max_length=20, null=True)),
                ('bankstatements_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('bureau_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('accounting_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('ppsr_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('originator', models.CharField(blank=True, max_length=2000, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('product', models.CharField(blank=True, max_length=2000, null=True)),
                ('insurance_premiums', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'efs_sales_ipf_applicationdata',
            },
        ),
        migrations.CreateModel(
            name='SalesOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ABN', models.CharField(blank=True, max_length=100, null=True)),
                ('transactionID', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('Insolvencies', models.BooleanField(blank=True, default=False, null=True)),
                ('Insolvencies_state', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=100, null=True)),
                ('Payment_Defaults', models.BooleanField(blank=True, default=False, null=True)),
                ('Payment_Defaults_state', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=100, null=True)),
                ('Mercantile_Enquiries', models.BooleanField(blank=True, default=False, null=True)),
                ('Mercantile_Enquiries_state', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=100, null=True)),
                ('Court_Judgements', models.BooleanField(blank=True, default=False, null=True)),
                ('Court_Judgements_state', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=100, null=True)),
                ('ATO_Tax_Default', models.BooleanField(blank=True, default=False, null=True)),
                ('ATO_Tax_Default_state', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=100, null=True)),
                ('Loans', models.BooleanField(blank=True, default=False, null=True)),
                ('Loans_state', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=100, null=True)),
                ('ANZSIC', models.BooleanField(blank=True, default=False, null=True)),
                ('ANZSIC_state', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=100, null=True)),
                ('Credit_score_threshold', models.CharField(blank=True, max_length=100, null=True)),
                ('Credit_score_threshold_state', models.CharField(blank=True, choices=[('below', 'Below Threshold'), ('above', 'Above Threshold')], default='above', max_length=100, null=True)),
                ('Sales_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='scf_ApplicationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('application_time', models.DateTimeField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('abn', models.CharField(blank=True, max_length=20, null=True)),
                ('acn', models.CharField(blank=True, max_length=20, null=True)),
                ('bankstatements_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('bureau_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('accounting_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('ppsr_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('originator', models.CharField(blank=True, max_length=2000, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('product', models.CharField(blank=True, max_length=2000, null=True)),
                ('insurance_premiums', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'efs_sales_scf_applicationdata',
            },
        ),
        migrations.CreateModel(
            name='tf_ApplicationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('application_time', models.DateTimeField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('abn', models.CharField(blank=True, max_length=20, null=True)),
                ('acn', models.CharField(blank=True, max_length=20, null=True)),
                ('bankstatements_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('bureau_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('accounting_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('ppsr_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('originator', models.CharField(blank=True, max_length=2000, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('product', models.CharField(blank=True, max_length=2000, null=True)),
                ('insurance_premiums', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'efs_sales_tf_applicationdata',
            },
        ),
    ]
