# Generated by Django 5.2.5 on 2025-08-21 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='applicationdata',
            table='efs_application_data_applicationdata',
        ),
        migrations.AlterModelTable(
            name='ipf_applicationdata',
            table='efs_application_data_ipf_applicationdata',
        ),
        migrations.AlterModelTable(
            name='scf_applicationdata',
            table='efs_application_data_scf_applicationdata',
        ),
        migrations.AlterModelTable(
            name='tf_applicationdata',
            table='efs_application_data_tf_applicationdata',
        ),
    ]
