# syntax=docker/dockerfile:1
FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# If you use psycopg[binary] you don't need libpq; keeping these packages helps for native builds.
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libpq-dev && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Copy project
COPY . .

EXPOSE 8000

# Command is also set in compose; this is a safe default
CMD ["bash","-c","python manage.py runserver 0.0.0.0:8000"]
