# Generated by Django 5.2.5 on 2025-08-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditDecisionParametersGlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originator', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_score_threshold', models.IntegerField(blank=True, default=500, null=True)),
                ('credit_score_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('credit_enquiries_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('court_actions_current_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('court_actions_resolved_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('payment_defaults_current_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('payment_defaults_resolved_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('insolvencies_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('ato_tax_default_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
