# Generated by Django 5.2.5 on 2026-01-14 06:00

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('early_payment_program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='scf_ApplicationInvoiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('abn', models.CharField(blank=True, max_length=15, null=True)),
                ('acn', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('debtor', models.CharField(blank=True, max_length=255, null=True)),
                ('date_funded', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount_funded', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('face_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sif_batch', models.CharField(blank=True, max_length=100, null=True)),
                ('inv_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
