# Generated by Django 5.2.5 on 2025-09-11 03:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('abn', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('abn', models.CharField(blank=True, max_length=20, null=True)),
                ('account_type', models.CharField(blank=True, max_length=255, null=True)),
                ('account_holder', models.CharField(blank=True, max_length=255, null=True)),
                ('account_holder_type', models.CharField(blank=True, max_length=50, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bsb', models.CharField(blank=True, max_length=10, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('available_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.bank', to_field='bank_id')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('abn', models.CharField(blank=True, max_length=20, null=True)),
                ('acn', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('suburb', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.bankaccount', to_field='account_id')),
            ],
        ),
        migrations.DeleteModel(
            name='ApplicationData',
        ),
        migrations.DeleteModel(
            name='IPF_ApplicationData',
        ),
        migrations.DeleteModel(
            name='SalesOverride',
        ),
        migrations.DeleteModel(
            name='scf_ApplicationData',
        ),
        migrations.DeleteModel(
            name='tf_ApplicationData',
        ),
    ]
