# Generated by Django 5.2.5 on 2025-09-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditDecisionParametersGlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originator', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_score_threshold', models.IntegerField(blank=True, default=500, null=True)),
                ('credit_score_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('credit_enquiries_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('court_actions_current_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('court_actions_resolved_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('payment_defaults_current_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('payment_defaults_resolved_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('insolvencies_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('ato_tax_default_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProductsGlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originator', models.CharField(blank=True, max_length=255, null=True)),
                ('term_loan_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('term_loan_duration_years', models.IntegerField(blank=True, null=True)),
                ('term_loan_duration_months', models.IntegerField(blank=True, null=True)),
                ('overdraft_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('overdraft_duration_years', models.IntegerField(blank=True, null=True)),
                ('overdraft_duration_months', models.IntegerField(blank=True, null=True)),
                ('credit_card_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('credit_card_duration_years', models.IntegerField(blank=True, null=True)),
                ('credit_card_duration_months', models.IntegerField(blank=True, null=True)),
                ('bulk_invoice_finance_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('single_invoice_finance_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('trade_finance_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('trade_finance_installments', models.JSONField(blank=True, null=True)),
                ('trade_finance_installment_frequency', models.JSONField(blank=True, null=True)),
                ('insurance_premium_funding_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('insurance_premium_funding_installments', models.JSONField(blank=True, null=True)),
                ('insurance_premium_funding_installment_frequency', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='ApplicationData',
        ),
        migrations.DeleteModel(
            name='IPF_ApplicationData',
        ),
        migrations.DeleteModel(
            name='SalesOverride',
        ),
        migrations.DeleteModel(
            name='scf_ApplicationData',
        ),
        migrations.DeleteModel(
            name='tf_ApplicationData',
        ),
    ]
