# Generated by Django 5.2.5 on 2025-10-02 08:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('element_type', models.CharField(choices=[('text', 'text'), ('table', 'table'), ('chart', 'chart'), ('figure', 'figure'), ('metadata', 'metadata')], max_length=20)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('start_offset', models.IntegerField(blank=True, null=True)),
                ('end_offset', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('table_json', models.JSONField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parser', models.CharField(max_length=100)),
                ('parser_version', models.CharField(default='v1', max_length=50)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='annualreportchart',
            name='report',
        ),
        migrations.RemoveField(
            model_name='annualreporttable',
            name='report',
        ),
        migrations.RemoveField(
            model_name='annualreporttext',
            name='report',
        ),
    ]
