# Generated by Django 5.2.5 on 2025-10-02 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunking', '0002_element_extractionrun_and_more'),
        ('ingestion', '0002_document_documentfile_delete_annualreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='ingestion.document'),
        ),
        migrations.AddField(
            model_name='extractionrun',
            name='document_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='ingestion.documentfile'),
        ),
        migrations.AddField(
            model_name='element',
            name='extraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='chunking.extractionrun'),
        ),
        migrations.DeleteModel(
            name='AnnualReportChart',
        ),
        migrations.DeleteModel(
            name='AnnualReportTable',
        ),
        migrations.DeleteModel(
            name='AnnualReportText',
        ),
        migrations.AddIndex(
            model_name='element',
            index=models.Index(fields=['document', 'element_type'], name='chunking_el_documen_a9e73f_idx'),
        ),
        migrations.AddIndex(
            model_name='element',
            index=models.Index(fields=['page_number'], name='chunking_el_page_nu_797fa0_idx'),
        ),
    ]
