# Generated by Django 5.2.5 on 2025-09-17 03:36

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_name', models.CharField(default='Default Memory Config', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('stm_max_tokens', models.IntegerField(default=8000)),
                ('attention_user_focus', models.BooleanField(default=False)),
                ('attention_recent_inputs', models.BooleanField(default=False)),
                ('attention_recurring_topics', models.BooleanField(default=False)),
                ('attention_custom_focus_rules', models.TextField(blank=True, null=True)),
                ('token_management_strategy', models.CharField(choices=[('preserve', 'Preserve'), ('compress', 'Compress'), ('summarize', 'Summarize')], default='preserve', max_length=50)),
                ('critical_keywords', models.TextField(blank=True, null=True)),
                ('overflow_policy', models.CharField(choices=[('discard_oldest', 'Discard Oldest'), ('transfer_to_ltm', 'Transfer to LTM'), ('compress_context', 'Compress Context')], default='discard_oldest', max_length=50)),
                ('episodic_conversation_history', models.BooleanField(default=False)),
                ('episodic_user_preferences', models.BooleanField(default=False)),
                ('episodic_user_behavior', models.BooleanField(default=False)),
                ('episodic_retention_duration', models.CharField(choices=[('session', 'This Session Only'), ('7d', '7 Days'), ('30d', '30 Days'), ('forever', 'Forever')], default='session', max_length=50)),
                ('framework', models.CharField(choices=[('langchain', 'Langchain'), ('llamaindex', 'LlamaIndex'), ('custom', 'Custom')], default='langchain', max_length=50)),
                ('semantic_enabled', models.BooleanField(default=False)),
                ('semantic_compliance_data', models.BooleanField(default=False)),
                ('procedural_enabled', models.BooleanField(default=False)),
                ('procedural_strict_workflows', models.BooleanField(default=False)),
                ('ltm_relevance_threshold', models.FloatField(default=0.7)),
                ('ltm_enable_rag', models.BooleanField(default=False)),
                ('consolidation_importance_based', models.BooleanField(default=False)),
                ('consolidation_frequency_based', models.BooleanField(default=False)),
                ('consolidation_explicit_commands', models.BooleanField(default=False)),
                ('decay_period_days', models.IntegerField(default=7)),
                ('feedback_explicit', models.BooleanField(default=False)),
                ('feedback_implicit', models.BooleanField(default=False)),
                ('adapt_decay_unused', models.BooleanField(default=False)),
                ('adapt_reinforce_frequent', models.BooleanField(default=False)),
                ('adapt_request_clarification', models.BooleanField(default=False)),
                ('integrate_pre_response', models.BooleanField(default=False)),
                ('integrate_mid_reasoning', models.BooleanField(default=False)),
                ('integrate_post_response', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'memory_configuration',
            },
        ),
        migrations.CreateModel(
            name='AgentSectionData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bot_name', models.CharField(blank=True, help_text='Name of the bot', max_length=255, null=True)),
                ('created_by', models.CharField(default='admin', help_text='User who created the bot', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Date the bot was created')),
                ('business_function', models.CharField(blank=True, max_length=255, null=True)),
                ('persona', models.TextField(blank=True, null=True)),
                ('selected_models', models.JSONField(blank=True, null=True)),
                ('persona_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('agent_archive', models.JSONField(blank=True, null=True)),
                ('memory_studio', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agent_section_data',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['persona_embedding'], m=16, name='agent_persona_hnsw_cosine', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('context_tokens', models.IntegerField(default=0)),
                ('overflow_policy', models.CharField(default='discard_oldest', max_length=50)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.agentsectiondata')),
            ],
            options={
                'db_table': 'agent_session',
            },
        ),
        migrations.CreateModel(
            name='AgentMemoryVector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('memory_type', models.CharField(choices=[('persona', 'Persona'), ('semantic', 'Semantic'), ('procedural', 'Procedural'), ('episodic', 'Episodic'), ('feedback', 'Feedback'), ('other', 'Other')], default='other', max_length=20)),
                ('source_table', models.CharField(blank=True, max_length=64, null=True)),
                ('source_pk', models.UUIDField(blank=True, null=True)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_vectors', to='core.agentsectiondata')),
            ],
            options={
                'db_table': 'agent_memory_vector',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='amv_hnsw_cosine', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.CreateModel(
            name='EpisodicMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('is_promoted', models.BooleanField(default=False)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodic_memories', to='core.agentsession')),
            ],
            options={
                'db_table': 'episodic_memory',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='episodic_hnsw_cosine', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.CreateModel(
            name='FeedbackMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('related_entity', models.CharField(max_length=255)),
                ('feedback_type', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('action_taken', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_memories', to='core.agentsectiondata')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_memories', to='core.memoryconfiguration')),
            ],
            options={
                'db_table': 'feedback_memory',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='feedback_hnsw_cosine', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.CreateModel(
            name='ProceduralMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(max_length=50)),
                ('condition_expression', models.TextField()),
                ('action', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedural_memories', to='core.agentsectiondata')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedural_memories', to='core.memoryconfiguration')),
            ],
            options={
                'db_table': 'procedural_memory',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='proc_rule_hnsw_cosine', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.CreateModel(
            name='SemanticMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=200)),
                ('value', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('key_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('value_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semantic_memories', to='core.agentsectiondata')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semantic_memories', to='core.memoryconfiguration')),
            ],
            options={
                'db_table': 'semantic_memory',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['value_embedding'], m=16, name='sem_value_hnsw_cosine', opclasses=['vector_cosine_ops']), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['key_embedding'], m=16, name='sem_key_hnsw_cosine', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
