# Generated by Django 5.2.5 on 2026-02-26 03:55

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_agentsectiondata_memory_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTurnMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=64)),
                ('ticket_label', models.CharField(blank=True, max_length=255, null=True)),
                ('abn', models.CharField(blank=True, max_length=11, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=64, null=True)),
                ('tier', models.CharField(choices=[('stm', 'Short Term'), ('ltm', 'Long Term')], default='stm', max_length=8)),
                ('input_text', models.TextField(blank=True, default='')),
                ('output_text', models.TextField(blank=True, default='')),
                ('compressed_text', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_memories', to='core.agentsectiondata')),
            ],
            options={
                'db_table': 'agent_turn_memory',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='atm_hnsw_cosine', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
