# Generated by Django 5.2.5 on 2026-02-26 05:49

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agentturnmemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentturnmemory',
            name='output_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
