# Generated by Django 5.2.5 on 2026-02-26 10:21

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_agentturnmemory_output_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentturnmemory',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AlterField(
            model_name='agentturnmemory',
            name='output_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
