# Generated by Django 5.2.5 on 2026-02-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_agentturnmemory_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceduralmemory',
            name='action',
            field=models.CharField(max_length=1000000),
        ),
    ]
