# Generated by Django 5.2.5 on 2025-09-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tf_Drawdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_drawndown', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date_drawndown', models.DateField(blank=True, null=True)),
                ('allocation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('abn', models.CharField(blank=True, max_length=20, null=True)),
                ('product', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'efs_lms_tf_drawdown',
            },
        ),
        migrations.CreateModel(
            name='tf_DrawdownData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('drawdown_time', models.DateTimeField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('abn', models.CharField(blank=True, max_length=20, null=True)),
                ('acn', models.CharField(blank=True, max_length=20, null=True)),
                ('bankstatements_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('bureau_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('accounting_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('ppsr_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('originator', models.CharField(blank=True, max_length=2000, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('product', models.CharField(blank=True, max_length=2000, null=True)),
                ('insurance_premiums', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'efs_lms_tf_drawdowndata',
            },
        ),
        migrations.CreateModel(
            name='tf_InvoiceRepayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_repaid', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date_repaid', models.DateField(blank=True, null=True)),
                ('allocation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('abn', models.CharField(blank=True, max_length=20, null=True)),
                ('product', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'efs_lms_tf_invoicerepayments',
            },
        ),
        migrations.CreateModel(
            name='tf_TransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(max_length=255)),
                ('debtor', models.CharField(blank=True, max_length=255, null=True)),
                ('due', models.DateField(blank=True, null=True)),
                ('amount_funded', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amount_repaid', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('face_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date_funded', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('abn', models.CharField(blank=True, max_length=20, null=True)),
                ('product', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'efs_lms_tf_transactiondetails',
            },
        ),
        migrations.CreateModel(
            name='tf_TransactionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(max_length=255, unique=True)),
                ('abn', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_funded', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amount_repaid', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'efs_lms_tf_transactionledger',
            },
        ),
    ]
