# Generated by Django 5.2.5 on 2025-09-09 04:04

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('abn', models.CharField(blank=True, max_length=11, null=True)),
                ('acn', models.CharField(blank=True, max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('financials', models.JSONField(blank=True, null=True)),
                ('profit_loss', models.JSONField(blank=True, null=True)),
                ('balance_sheet', models.JSONField(blank=True, null=True)),
                ('subsidiaries', models.JSONField(blank=True, default=list, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('abn', models.CharField(blank=True, max_length=15, null=True)),
                ('search_date', models.DateField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('change_number', models.CharField(blank=True, max_length=20, null=True)),
                ('change_time', models.DateTimeField(blank=True, null=True)),
                ('registration_kind', models.CharField(blank=True, max_length=255, null=True)),
                ('is_migrated', models.BooleanField(blank=True, null=True)),
                ('is_transitional', models.BooleanField(blank=True, null=True)),
                ('grantor_organisation_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('grantor_organisation_identifier_type', models.CharField(blank=True, max_length=255, null=True)),
                ('grantor_organisation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('collateral_class_type', models.CharField(blank=True, max_length=255, null=True)),
                ('collateral_type', models.CharField(blank=True, max_length=255, null=True)),
                ('collateral_class_description', models.CharField(blank=True, null=True)),
                ('are_proceeds_claimed', models.BooleanField(blank=True, null=True)),
                ('proceeds_claimed_description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_security_interest_registration_kind', models.BooleanField(blank=True, null=True)),
                ('are_assets_subject_to_control', models.BooleanField(blank=True, null=True)),
                ('is_inventory', models.BooleanField(blank=True, null=True)),
                ('is_pmsi', models.BooleanField(blank=True, null=True)),
                ('is_subordinate', models.BooleanField(blank=True, null=True)),
                ('giving_of_notice_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('security_party_groups', models.JSONField(blank=True, null=True)),
                ('grantors', models.JSONField(blank=True, null=True)),
                ('address_for_service', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abn', models.CharField(blank=True, max_length=15, null=True)),
                ('acn', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('debtor', models.CharField(blank=True, max_length=255, null=True)),
                ('date_funded', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount_funded', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('face_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sif_batch', models.CharField(blank=True, max_length=100, null=True)),
                ('inv_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'efs_financial_invoicedata',
                'unique_together': {('abn', 'inv_number')},
            },
        ),
        migrations.CreateModel(
            name='LedgerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abn', models.CharField(blank=True, max_length=15, null=True)),
                ('transaction_id', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('debtor', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('repayment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'efs_financial_ledgerdata',
                'unique_together': {('abn', 'invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='scf_InvoiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abn', models.CharField(blank=True, max_length=15, null=True)),
                ('acn', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('debtor', models.CharField(blank=True, max_length=255, null=True)),
                ('date_funded', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount_funded', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('face_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sif_batch', models.CharField(blank=True, max_length=100, null=True)),
                ('inv_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'efs_financial_scf_invoicedata',
                'unique_together': {('abn', 'inv_number')},
            },
        ),
        migrations.CreateModel(
            name='tf_InvoiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abn', models.CharField(blank=True, max_length=15, null=True)),
                ('acn', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('debtor', models.CharField(blank=True, max_length=255, null=True)),
                ('date_funded', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount_funded', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('face_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sif_batch', models.CharField(blank=True, max_length=100, null=True)),
                ('inv_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'efs_financial_tf_invoicedata',
                'unique_together': {('abn', 'inv_number')},
            },
        ),
    ]
