# Generated by Django 5.2.5 on 2025-09-24 10:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_uploadedledgerdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadAPLedgerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abn', models.CharField(blank=True, max_length=15, null=True)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('debtor', models.CharField(blank=True, max_length=255, null=True)),
                ('aged_receivables', models.CharField(blank=True, max_length=50, null=True)),
                ('days_0_30', models.CharField(blank=True, max_length=50, null=True, verbose_name='0-30 days')),
                ('days_31_60', models.CharField(blank=True, max_length=50, null=True, verbose_name='31-60 days')),
                ('days_61_90', models.CharField(blank=True, max_length=50, null=True, verbose_name='61-90 days')),
                ('days_90_plus', models.CharField(blank=True, max_length=50, null=True, verbose_name='90+ days')),
            ],
            options={
                'db_table': 'uploaded_ap_ledger_data',
            },
        ),
    ]
