# Generated by Django 5.2.5 on 2025-09-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_uploadapledgerdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadapledgerdata',
            old_name='aged_receivables',
            new_name='aged_payables',
        ),
        migrations.RenameField(
            model_name='uploadapledgerdata',
            old_name='debtor',
            new_name='creditor',
        ),
    ]
