# Generated by Django 5.2.5 on 2025-09-25 02:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_aged_receivables_uploadapledgerdata_aged_payables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadapledgerdata',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedledgerdata',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadapledgerdata',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='uploadedledgerdata',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
