# Generated by Django 5.2.5 on 2025-09-25 03:52

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_uploadapledgerdata_notes_uploadedledgerdata_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatementNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='External/shared transaction identifier (UUID).')),
                ('abn', models.CharField(db_index=True, help_text='Australian Business Number (11 digits). Keep as text to preserve leading zeros.', max_length=20)),
                ('financial_data_type', models.CharField(db_index=True, help_text="Kind of financial data these notes relate to (e.g., 'P&L', 'Balance Sheet', 'Cashflow').", max_length=100)),
                ('notes', models.TextField(help_text='Free-text notes. Use for long-form content (multi-page allowed).')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'financial_statement_notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='financial_s_transac_5f9758_idx'), models.Index(fields=['abn'], name='financial_s_abn_3b2a7c_idx'), models.Index(fields=['financial_data_type'], name='financial_s_financi_a5de86_idx')],
            },
        ),
    ]
