# Generated by Django 5.2.5 on 2025-09-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_financialstatementnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdata',
            name='cash_flow',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialdata',
            name='financial_statement_notes',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
