# Generated by Django 5.2.5 on 2025-09-29 02:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_financialdata_cash_flow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='transaction_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
