# Generated by Django 5.2.5 on 2025-09-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_registration_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
