# Generated by Django 5.2.5 on 2025-10-12 22:17

import core.models
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_registration_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('year_of_manufacture', models.IntegerField(blank=True, null=True)),
                ('age_years', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('serial_no', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('vin', models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[core.models.validate_vin])),
                ('registration_no', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['make', 'model'], name='core_asset_make_5e9d1b_idx'), models.Index(fields=['type'], name='core_asset_type_ce16be_idx'), models.Index(fields=['year_of_manufacture'], name='core_asset_year_of_3cae36_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.UUIDField(db_index=True)),
                ('asset_id', models.UUIDField(db_index=True)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('condition_note', models.TextField(blank=True, null=True)),
                ('abn', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('row_raw', models.JSONField(blank=True, default=dict)),
                ('extras', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['abn'], name='core_asseti_abn_0c653b_idx'), models.Index(fields=['transaction_id'], name='core_asseti_transac_82f1f9_idx'), models.Index(fields=['source_id'], name='core_asseti_source__61c66b_idx'), models.Index(fields=['asset_id'], name='core_asseti_asset_i_c4ec47_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetSource',
            fields=[
                ('source_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=200)),
                ('schedule_title', models.CharField(blank=True, max_length=500, null=True)),
                ('as_of_date', models.DateField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=500, null=True)),
                ('file_checksum', models.CharField(blank=True, max_length=128, null=True)),
                ('currency', models.CharField(default='AUD', max_length=3)),
                ('tax_label', models.CharField(blank=True, max_length=50, null=True)),
                ('amounts_include_tax', models.BooleanField(default=False)),
                ('abn', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['abn'], name='core_assets_abn_1709fa_idx'), models.Index(fields=['transaction_id'], name='core_assets_transac_b88307_idx'), models.Index(fields=['as_of_date'], name='core_assets_as_of_d_8d529f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetValuation',
            fields=[
                ('valuation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.UUIDField(db_index=True)),
                ('source_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('valuation_type', models.CharField(choices=[('FMV', 'Fair Market Value'), ('FSV', 'Forced Sale Value'), ('OLV', 'Orderly Liquidation Value')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='AUD', max_length=3)),
                ('amount_includes_tax', models.BooleanField(default=False)),
                ('as_of_date', models.DateField(blank=True, null=True)),
                ('abn', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['asset_id', 'valuation_type', '-as_of_date'], name='core_assetv_asset_i_4750c4_idx'), models.Index(fields=['abn'], name='core_assetv_abn_4a02ba_idx'), models.Index(fields=['transaction_id'], name='core_assetv_transac_956513_idx')],
            },
        ),
    ]
