# Generated by Django 5.2.5 on 2025-10-13 04:44

import core.models
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_asset_assetitem_assetsource_assetvaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetScheduleRow',
            fields=[
                ('row_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(default='Schedule Upload', max_length=200)),
                ('schedule_title', models.CharField(blank=True, max_length=500, null=True)),
                ('source_as_of_date', models.DateField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=500, null=True)),
                ('file_checksum', models.CharField(blank=True, max_length=128, null=True)),
                ('currency', models.CharField(default='AUD', max_length=3)),
                ('tax_label', models.CharField(blank=True, max_length=50, null=True)),
                ('amounts_include_tax', models.BooleanField(default=False)),
                ('abn', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('make', models.CharField(default='Unknown', max_length=200)),
                ('model', models.CharField(default='Unknown', max_length=200)),
                ('type', models.CharField(default='Asset', max_length=200)),
                ('year_of_manufacture', models.IntegerField(blank=True, null=True)),
                ('age_years', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('serial_no', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('vin', models.CharField(blank=True, max_length=17, null=True, validators=[core.models.validate_vin])),
                ('registration_no', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('condition_note', models.TextField(blank=True, null=True)),
                ('row_raw', models.JSONField(blank=True, default=dict)),
                ('extras', models.JSONField(blank=True, default=dict)),
                ('valuation_as_of_date', models.DateField(blank=True, null=True)),
                ('fmv_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fsv_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('olv_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valuation_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='AssetItem',
        ),
        migrations.DeleteModel(
            name='AssetSource',
        ),
        migrations.DeleteModel(
            name='AssetValuation',
        ),
        migrations.AddIndex(
            model_name='assetschedulerow',
            index=models.Index(fields=['abn'], name='core_assets_abn_212dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='assetschedulerow',
            index=models.Index(fields=['transaction_id'], name='core_assets_transac_1fedb1_idx'),
        ),
        migrations.AddIndex(
            model_name='assetschedulerow',
            index=models.Index(fields=['source_as_of_date'], name='core_assets_source__151517_idx'),
        ),
        migrations.AddIndex(
            model_name='assetschedulerow',
            index=models.Index(fields=['vin'], name='core_assets_vin_e88826_idx'),
        ),
        migrations.AddIndex(
            model_name='assetschedulerow',
            index=models.Index(fields=['serial_no'], name='core_assets_serial__2b2130_idx'),
        ),
        migrations.AddIndex(
            model_name='assetschedulerow',
            index=models.Index(fields=['make', 'model'], name='core_assets_make_35ff89_idx'),
        ),
        migrations.AddIndex(
            model_name='assetschedulerow',
            index=models.Index(fields=['type'], name='core_assets_type_eadcfd_idx'),
        ),
    ]
