# Generated by Django 5.2.5 on 2025-10-13 07:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_assetschedulerow_delete_asset_delete_assetitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetAssetValueSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('abn', models.CharField(db_index=True, max_length=32)),
                ('transaction_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source_tab', models.CharField(choices=[('ASSETS', 'Assets'), ('AR', 'Accounts Receivable')], max_length=16)),
                ('advance_rate_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('selected_total_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('available_funds_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['abn', 'transaction_id', 'source_tab'], name='core_netass_abn_74e262_idx')],
            },
        ),
        migrations.CreateModel(
            name='NAVAssetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, default='', max_length=128)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('type', models.CharField(blank=True, default='', max_length=128)),
                ('year_of_manufacture', models.CharField(blank=True, default='', max_length=16)),
                ('fmv_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('fsv_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_lines', to='core.netassetvaluesnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='NAVARLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor_name', models.CharField(blank=True, default='', max_length=256)),
                ('aged_current', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('d0_30', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('d31_60', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('d61_90', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('d90_plus', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('nominated', models.BooleanField(default=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_lines', to='core.netassetvaluesnapshot')),
            ],
        ),
    ]
