# Generated by Django 5.2.5 on 2025-10-23 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_netassetvaluesnapshot_navassetline_navarline'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/asset_lists/')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(blank=True, max_length=100, null=True)),
                ('asset', models.CharField(blank=True, max_length=255, null=True)),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=255, null=True)),
                ('rego_no', models.CharField(blank=True, max_length=255, null=True)),
                ('year_of_manufacture', models.IntegerField(blank=True, null=True)),
                ('fair_market_value_ex_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('orderly_liquidation_value_ex_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.assetupload')),
            ],
            options={
                'indexes': [models.Index(fields=['asset_number'], name='core_asseti_asset_n_591019_idx'), models.Index(fields=['make'], name='core_asseti_make_980228_idx')],
            },
        ),
    ]
