# Generated by Django 5.2.5 on 2025-10-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_assetupload_assetitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetitem',
            name='abn',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assetitem',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
