# Generated by Django 5.2.5 on 2025-10-23 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ppeasset_delete_assetitem_delete_assetupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='NAVPlantandequipmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, default='', max_length=128)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('type', models.CharField(blank=True, default='', max_length=128)),
                ('year_of_manufacture', models.CharField(blank=True, default='', max_length=16)),
                ('fmv_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('fsv_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ],
        ),
        migrations.RenameIndex(
            model_name='ppeasset',
            new_name='ppe_assets_abn_55e2d5_idx',
            old_name='core_ppe_abn_idx',
        ),
        migrations.RenameIndex(
            model_name='ppeasset',
            new_name='ppe_assets_transac_4180f1_idx',
            old_name='core_ppe_tx_idx',
        ),
        migrations.RenameIndex(
            model_name='ppeasset',
            new_name='ppe_assets_upload__30dcb8_idx',
            old_name='core_ppe_upgrp_idx',
        ),
        migrations.RenameIndex(
            model_name='ppeasset',
            new_name='ppe_assets_asset_n_404fdf_idx',
            old_name='core_ppe_assetnum_idx',
        ),
        migrations.RenameIndex(
            model_name='ppeasset',
            new_name='ppe_assets_make_59700c_idx',
            old_name='core_ppe_make_idx',
        ),
        migrations.RenameIndex(
            model_name='ppeasset',
            new_name='ppe_assets_serial__dff209_idx',
            old_name='core_ppe_serial_idx',
        ),
        migrations.RenameIndex(
            model_name='ppeasset',
            new_name='ppe_assets_rego_no_9b11af_idx',
            old_name='core_ppe_rego_idx',
        ),
        migrations.AddField(
            model_name='navplantandequipmentline',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_equipment_lines', to='core.netassetvaluesnapshot'),
        ),
    ]
