# Generated by Django 5.2.5 on 2025-10-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_navplantandequipmentline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='acn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
