# Generated by Django 5.2.5 on 2025-10-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_registration_acn'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoicedata',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ledgerdata',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='scf_invoicedata',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tf_invoicedata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assetschedulerow',
            name='acn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='financialstatementnotes',
            name='acn',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ledgerdata',
            name='acn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='netassetvaluesnapshot',
            name='acn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ppeasset',
            name='acn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uploadapledgerdata',
            name='acn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uploadedledgerdata',
            name='acn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatementnotes',
            name='financial_data_type',
            field=models.CharField(db_index=True, help_text="What these notes refer to (e.g. 'AR Ledger', 'Assets', 'Liabilities').", max_length=100),
        ),
        migrations.AlterField(
            model_name='financialstatementnotes',
            name='notes',
            field=models.TextField(help_text='Free-text notes. Can be long / multi-line.'),
        ),
        migrations.AddIndex(
            model_name='assetschedulerow',
            index=models.Index(fields=['acn'], name='core_assets_acn_391f4e_idx'),
        ),
        migrations.AddIndex(
            model_name='financialstatementnotes',
            index=models.Index(fields=['acn'], name='financial_s_acn_7d8088_idx'),
        ),
        migrations.AddIndex(
            model_name='netassetvaluesnapshot',
            index=models.Index(fields=['acn', 'transaction_id', 'source_tab'], name='core_netass_acn_902d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='ppeasset',
            index=models.Index(fields=['acn'], name='ppe_assets_acn_ec2f6e_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['transaction_id'], name='core_regist_transac_7c1591_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['abn'], name='core_regist_abn_c32c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['acn'], name='core_regist_acn_01e9eb_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['registration_number'], name='core_regist_registr_809791_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadapledgerdata',
            index=models.Index(fields=['abn'], name='uploaded_ap_abn_d1ab98_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadapledgerdata',
            index=models.Index(fields=['acn'], name='uploaded_ap_acn_bca3ca_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadapledgerdata',
            index=models.Index(fields=['transaction_id'], name='uploaded_ap_transac_39863d_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedledgerdata',
            index=models.Index(fields=['abn'], name='uploaded_le_abn_fd89bc_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedledgerdata',
            index=models.Index(fields=['acn'], name='uploaded_le_acn_ce98eb_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedledgerdata',
            index=models.Index(fields=['transaction_id'], name='uploaded_le_transac_c16c60_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoicedata',
            constraint=models.UniqueConstraint(condition=models.Q(('abn__isnull', False), models.Q(('abn', ''), _negated=True)), fields=('abn', 'inv_number'), name='uniq_invoice_by_abn'),
        ),
        migrations.AddConstraint(
            model_name='invoicedata',
            constraint=models.UniqueConstraint(condition=models.Q(('acn__isnull', False), models.Q(('acn', ''), _negated=True)), fields=('acn', 'inv_number'), name='uniq_invoice_by_acn'),
        ),
        migrations.AddConstraint(
            model_name='ledgerdata',
            constraint=models.UniqueConstraint(condition=models.Q(('abn__isnull', False), models.Q(('abn', ''), _negated=True)), fields=('abn', 'invoice_number'), name='uniq_ledger_by_abn_invnum'),
        ),
        migrations.AddConstraint(
            model_name='ledgerdata',
            constraint=models.UniqueConstraint(condition=models.Q(('acn__isnull', False), models.Q(('acn', ''), _negated=True)), fields=('acn', 'invoice_number'), name='uniq_ledger_by_acn_invnum'),
        ),
        migrations.AddConstraint(
            model_name='scf_invoicedata',
            constraint=models.UniqueConstraint(condition=models.Q(('abn__isnull', False), models.Q(('abn', ''), _negated=True)), fields=('abn', 'inv_number'), name='uniq_scf_invoice_by_abn'),
        ),
        migrations.AddConstraint(
            model_name='scf_invoicedata',
            constraint=models.UniqueConstraint(condition=models.Q(('acn__isnull', False), models.Q(('acn', ''), _negated=True)), fields=('acn', 'inv_number'), name='uniq_scf_invoice_by_acn'),
        ),
        migrations.AddConstraint(
            model_name='tf_invoicedata',
            constraint=models.UniqueConstraint(condition=models.Q(('abn__isnull', False), models.Q(('abn', ''), _negated=True)), fields=('abn', 'inv_number'), name='uniq_tf_invoice_by_abn'),
        ),
        migrations.AddConstraint(
            model_name='tf_invoicedata',
            constraint=models.UniqueConstraint(condition=models.Q(('acn__isnull', False), models.Q(('acn', ''), _negated=True)), fields=('acn', 'inv_number'), name='uniq_tf_invoice_by_acn'),
        ),
    ]
