# Generated by Django 5.2.5 on 2025-10-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_invoicedata_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netassetvaluesnapshot',
            name='abn',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
