# Generated by Django 5.2.5 on 2025-10-28 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_netassetvaluesnapshot_abn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netassetvaluesnapshot',
            name='source_tab',
            field=models.CharField(choices=[('ASSETS', 'Assets'), ('AR', 'Accounts Receivable'), ('LIABILITIES', 'Liabilities')], max_length=16),
        ),
        migrations.CreateModel(
            name='NAVLiabilityLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_limit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('lender', models.CharField(blank=True, default='', max_length=256)),
                ('product', models.CharField(blank=True, default='', max_length=256)),
                ('current_balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('due_date', models.CharField(blank=True, default='', max_length=64)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liability_lines', to='core.netassetvaluesnapshot')),
            ],
        ),
    ]
