# Generated by Django 5.2.5 on 2025-12-08 05:35

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_navassetline_bv_amount_navassetline_lease_os_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtorsCreditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='External/shared transaction identifier (UUID).')),
                ('description', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=100)),
                ('abn', models.CharField(max_length=20)),
                ('acn', models.CharField(max_length=20)),
                ('credit_enquiries', models.IntegerField()),
                ('report', models.JSONField()),
                ('debtor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('debtor_abn', models.CharField(blank=True, max_length=20, null=True)),
                ('debtor_acn', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'debtors_credit reports',
                'verbose_name_plural': 'debtors_credit reports',
            },
        ),
        migrations.CreateModel(
            name='InvoiceDataUploaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abn', models.CharField(blank=True, max_length=15, null=True)),
                ('acn', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('debtor', models.CharField(blank=True, max_length=255, null=True)),
                ('date_funded', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('invoice_state', models.CharField(blank=True, max_length=100, null=True)),
                ('date_paid', models.DateField(blank=True, null=True, verbose_name='Date Paid')),
                ('amount_funded', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('face_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sif_batch', models.CharField(blank=True, max_length=100, null=True)),
                ('inv_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'InvoiceData-uploaded',
                'verbose_name_plural': 'InvoiceData-uploaded',
                'db_table': 'efs_financial_invoicedata_uploaded',
                'constraints': [models.UniqueConstraint(condition=models.Q(('abn__isnull', False), models.Q(('abn', ''), _negated=True)), fields=('abn', 'inv_number'), name='uniq_uploaded_invoice_by_abn'), models.UniqueConstraint(condition=models.Q(('acn__isnull', False), models.Q(('acn', ''), _negated=True)), fields=('acn', 'inv_number'), name='uniq_uploaded_invoice_by_acn')],
            },
        ),
    ]
