# Generated by Django 5.2.5 on 2025-12-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_debtorscreditreport_invoicedatauploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtorscreditreport',
            name='debtor_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debtorscreditreport',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
