# Generated by Django 5.2.5 on 2025-12-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_debtorscreditreport_debtor_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedatauploaded',
            name='approve_reject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
