# Generated by Django 5.2.5 on 2026-02-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_invoicedatauploaded_approve_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedata',
            name='approve_reject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
