# Generated by Django 5.2.5 on 2026-02-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_atopaymentplaninstalment_businessactivitystatement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessactivitystatement',
            name='abn',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessactivitystatement',
            name='acn',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessactivitystatement',
            name='biller_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
