# Generated by Django 5.2.5 on 2026-02-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_businessactivitystatement_abn_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessactivitystatement',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='businessactivitystatement',
            name='core_busine_transac_d823d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='businessactivitystatement',
            name='core_busine_abn_265e80_idx',
        ),
        migrations.RemoveIndex(
            model_name='businessactivitystatement',
            name='core_busine_origina_2719a0_idx',
        ),
        migrations.AlterField(
            model_name='businessactivitystatement',
            name='bpay_reference_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessactivitystatement',
            name='direct_credit_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessactivitystatement',
            name='direct_credit_account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessactivitystatement',
            name='direct_credit_bsb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessactivitystatement',
            name='direct_credit_institution_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessactivitystatement',
            name='direct_credit_reference_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessactivitystatement',
            name='document_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessactivitystatement',
            name='form_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessactivitystatement',
            name='gst_accounting_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
