# Generated by Django 5.2.5 on 2026-02-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_businessactivitystatement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedatauploaded',
            name='originator',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Originator'),
        ),
    ]
