# Generated by Django 5.2.5 on 2026-02-16 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_invoicedatauploaded_originator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedatauploaded',
            name='originator',
        ),
    ]
