# Generated by Django 5.2.5 on 2026-02-23 04:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_navarline_adj_ec_navarline_advance_rate_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AP_InvoiceDataUploaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abn', models.CharField(blank=True, max_length=15, null=True)),
                ('acn', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('creditor', models.CharField(blank=True, max_length=255, null=True)),
                ('date_funded', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('invoice_state', models.CharField(blank=True, max_length=100, null=True)),
                ('date_paid', models.DateField(blank=True, null=True, verbose_name='Date Paid')),
                ('amount_funded', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('face_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sif_batch', models.CharField(blank=True, max_length=100, null=True)),
                ('inv_number', models.CharField(blank=True, max_length=50, null=True)),
                ('approve_reject', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'AP InvoiceData-uploaded',
                'verbose_name_plural': 'AP InvoiceData-uploaded',
                'db_table': 'efs_financial_ap_invoicedata_uploaded',
                'constraints': [models.UniqueConstraint(condition=models.Q(('abn__isnull', False), models.Q(('abn', ''), _negated=True)), fields=('abn', 'inv_number'), name='uniq_ap_uploaded_invoice_by_abn'), models.UniqueConstraint(condition=models.Q(('acn__isnull', False), models.Q(('acn', ''), _negated=True)), fields=('acn', 'inv_number'), name='uniq_ap_uploaded_invoice_by_acn')],
            },
        ),
    ]
