# Generated by Django 5.2.5 on 2025-09-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementsGlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originator', models.CharField(blank=True, max_length=255, null=True)),
                ('debt_serviceability_coverage', models.FloatField(blank=True, default=2.5, null=True)),
                ('debt_serviceability_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('inflow_outflow_ratio', models.FloatField(blank=True, default=2.5, null=True)),
                ('inflow_outflow_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('expense_category_1', models.IntegerField(blank=True, default=1, null=True)),
                ('expense_category_1_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('expense_category_2', models.IntegerField(blank=True, default=1, null=True)),
                ('expense_category_2_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('expense_category_3', models.IntegerField(blank=True, default=1, null=True)),
                ('expense_category_3_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('expense_category_4', models.IntegerField(blank=True, default=1, null=True)),
                ('expense_category_4_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('expense_category_5', models.IntegerField(blank=True, default=1, null=True)),
                ('expense_category_5_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CreditDecisionParametersGlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originator', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_score_threshold', models.IntegerField(blank=True, default=500, null=True)),
                ('credit_score_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('credit_enquiries_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('court_actions_current_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('court_actions_resolved_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('payment_defaults_current_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('payment_defaults_resolved_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('insolvencies_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('ato_tax_default_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FinancialsGlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originator', models.CharField(blank=True, max_length=255, null=True)),
                ('ebitda_margin', models.FloatField(blank=True, default=0.5, null=True)),
                ('ebitda_margin_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('debt_to_equity_ratio', models.FloatField(blank=True, default=2.5, null=True)),
                ('debt_to_equity_ratio_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('liquidity_ratio', models.FloatField(blank=True, default=2.5, null=True)),
                ('liquidity_ratio_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProductsGlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originator', models.CharField(blank=True, max_length=255, null=True)),
                ('term_loan_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('term_loan_duration_years', models.IntegerField(blank=True, null=True)),
                ('term_loan_duration_months', models.IntegerField(blank=True, null=True)),
                ('overdraft_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('overdraft_duration_years', models.IntegerField(blank=True, null=True)),
                ('overdraft_duration_months', models.IntegerField(blank=True, null=True)),
                ('credit_card_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('credit_card_duration_years', models.IntegerField(blank=True, null=True)),
                ('credit_card_duration_months', models.IntegerField(blank=True, null=True)),
                ('bulk_invoice_finance_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('single_invoice_finance_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('trade_finance_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('trade_finance_installments', models.JSONField(blank=True, null=True)),
                ('trade_finance_installment_frequency', models.JSONField(blank=True, null=True)),
                ('insurance_premium_funding_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('insurance_premium_funding_installments', models.JSONField(blank=True, null=True)),
                ('insurance_premium_funding_installment_frequency', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
