# Generated by Django 5.2.5 on 2025-10-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdata',
            name='link_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='applicationdata',
            name='links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ipfapplicationdata',
            name='link_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ipfapplicationdata',
            name='links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scfapplicationdata',
            name='link_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scfapplicationdata',
            name='links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tfapplicationdata',
            name='link_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tfapplicationdata',
            name='links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='applicationdata',
            name='abn',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ipfapplicationdata',
            name='abn',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scfapplicationdata',
            name='abn',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tfapplicationdata',
            name='abn',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
