# Generated by Django 5.2.5 on 2025-10-27 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregate', '0002_applicationdata_link_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationdata',
            old_name='contact_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='ipfapplicationdata',
            old_name='contact_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='scfapplicationdata',
            old_name='contact_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='tfapplicationdata',
            old_name='contact_name',
            new_name='company_name',
        ),
    ]
