# Generated by Django 5.2.5 on 2026-02-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregate', '0003_rename_contact_name_applicationdata_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originator', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('product', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('condition_type', models.CharField(choices=[('pre', 'PRE-Settlement'), ('post', 'POST-Settlement')], db_index=True, max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(max_length=255)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'deal_conditions',
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['originator', 'company_name'], name='deal_condit_origina_df0945_idx'), models.Index(fields=['transaction_id'], name='deal_condit_transac_179e3a_idx'), models.Index(fields=['condition_type', 'date_created'], name='deal_condit_conditi_456962_idx')],
            },
        ),
    ]
