# Generated by Django 5.2.5 on 2026-02-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregate', '0004_dealcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepremiumfundingterms',
            name='transaction_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicefinanceterms',
            name='transaction_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='supplychainfinanceterms',
            name='transaction_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tradefinanceterms',
            name='transaction_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
