# Generated by Django 5.2.5 on 2026-02-11 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregate', '0005_insurancepremiumfundingterms_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancepremiumfundingterms',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='invoicefinanceterms',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='supplychainfinanceterms',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='tradefinanceterms',
            name='transaction_id',
        ),
    ]
